#!/bin/bash

file='/etc/passwd'
if [ ! -f "${file}" ] ; then
        printf '%s is not exists\n' "$file"
        exit 1
fi

while read -r line; do
        shell="$(printf '%s'  $line | cut -d: -f7)"
        if [ "$shell" = '/bin/bash' ] ; then
                username="$(printf '%s' $line | cut -d: -f1)"
                printf '%s\n' $username
        fi
done < ${file}

